# Generated by Django 3.2.5 on 2021-07-21 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('serial_number', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='numeric, alphabet or hylien', regex='^[0-9a-zA-Z-]+$')], verbose_name='S/N')),
                ('display_name', models.CharField(blank=True, max_length=128, verbose_name='Display Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
